image: Visual Studio 2019

before_build:
- nuget restore
- choco install opencover.portable
- choco install codecov

build:
  project: CodecovProject.sln
  verbosity: minimal

test_script:
- OpenCover.Console.exe -register:user -target:"%xunit20%\xunit.console.x86.exe" -targetargs:".\CoreDemoApp.Tests\bin\Debug\CoreDemoApp.Tests.dll -noshadow" -filter:"+[UnitTestTargetProject*]* -[CoreDemoApp.Tests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"
